# Generated by Django 4.2.30 on 2026-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(default='P3', max_length=2),
        ),
    ]
