# Generated by Django 4.2.30 on 2026-04-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
