# Generated by Django 4.2.30 on 2026-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_sede_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
