# Generated by Django 4.2.30 on 2026-04-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='impacto',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgencia',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10, null=True),
        ),
    ]
