# Generated by Django 5.2.13 on 2026-05-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Progreso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
    ]
